

SELECT
S_NO,
CUSTOMER_ID,
CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME,
UPPER(COMPANY) AS COMPANY,
CONCAT(CITY,', ',COUNTRY) AS LOCATION,
CONCAT(PHONE_PERSONAL,', ',PHONE_OFFICE) AS CONTACT_NUMBER,
EMAIL,
SUBSCRIPTION_DATE,
WEBSITE
from {{ ref("customers") }}